# -*- coding: utf-8 -*-
"""kalpi_stategy_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jvl7Qd9rGaNUI_5xP-JE0QKN4dxs_31_

# Kalpi.ai Assignment

## Web Agent Algorithm

1. Navogate to Kalpi.ai
2. Click on Product Overview -> Strategy Builder

3. Click on Universe Box
	- Select Universe Dropdown
	- Choose a Universe

4. Click on filters box
	- Click on add condition
	- Add operator and number
	- repeat for list of conditions

5. Click on Ranking and Scoring
	- Select what metrics you want for the ranking
	- repeat for items in list

6. Click on weights
	- Enter No of Stocks
	- Select either equal weight or metric weight


Bare minimum needed
Universe
Ranking metric

## Non-Web Algorithm

1. Get user description for strategy
    - Make a detailed implementation based description of the strategy given by the user.

2. Take the detailed report and choose a universe from which to select stocks

3. Make a list of filtration metrics relevant to the strategy
    - assign greater than or less than operator and a comparision value

4. Make a list of metrics on which to score and rank stocks

5. Select the top n no of stocks to put
    - Ask equal or metric weight
    - if metric weight Select metrics for metrics
"""

from typing import TypedDict, Annotated, List, Tuple, Literal, Optional

class FilterCondition(TypedDict):
    metric: str
    operator: Literal["<", ">", "<=", ">=", "=="]
    compare_type: Literal["value", "metric"]
    value: Optional[float]
    compare_metric: Optional[str]

class Reasoning(TypedDict):
    universe: str
    filter: str
    rank: str
    weightage: str
    modification: str

universes_constant = ["All Universe", "Nifty 500", 'Nifty 200', "Nifty 100", "Nifty 50", "Nifty Next 50", "Nifty Total Market",
             "Nifty Midcap 150", "Nifty Midcap 100", "Nifty Midcap 50", "Nifty Smallcap 250", "Nifty Smallcap 100",
             "Nifty Smallcap 50", "Nifty Microcap 250", "NIFTY MIDSMALLCAP 400", "Nifty LargeMidcap 250", "NIFTY FNO"]

metrics_constant = ['Close Price', 'High Price', 'Low Price', 'Open Price', 'Volume', 'ADX 14', 'ATR 14', 'Bollinger Bands Lower',
                    'Bollinger Bands Middle', 'Bollinger Bands Upper', 'CCI 14', 'EMA 100', 'EMA 10', 'EMA 15', 'EMA 20', 'EMA 200',
                    'EMA 5', 'EMA 50', 'MACD', 'MACD Histogram', 'MACD Signal', 'MFI 14', 'Momentum 10', 'OBV', 'PPO', 'RSI 14', 'SMA 100',
                    'SMA 10', 'SMA 15', 'SMA 20', 'SMA 200', 'SMA 5', 'SMA 50', 'Stochastic Slow D', 'Stochastic Slow K', 'Williams %R 14',
                    'WMA 100', 'WMA 10', 'WMA 15', 'WMA 20', 'WMA 200', 'WMA 5', 'WMA 50', 'EBITDA Q', 'EBITDA growth QoQ', 'EBITDA margin Q',
                    'EPS growth QoQ', 'EPS Q', 'Gross Profit Q', 'EBITDA growth YoY', 'EPS growth YoY', 'Profit growth YoY', 'Sales growth YoY',
                    'Profit after Tax Q', 'Net profit margin Q', 'Operating Profit Q', 'PBT Q', 'Profit growth QoQ', 'Sales growth QoQ',
                    'Net Revenue Q', 'EBIT Q', 'Interest Expense Q', 'Depreciation Q', 'Income Tax Q', 'Extraordinary Items Q', 'Other Income Q',
                    'Equity Capital Q', 'Operating Margin Q', 'Gross Margin Q', 'Operating Profit Growth YoY', 'PBT Growth YoY',
                    'EBIT Growth YoY', 'Interest Expense Growth YoY', 'Depreciation Growth YoY', 'Operating Profit Growth QoQ',
                    'PBT Growth QoQ', 'EBIT Growth QoQ', 'Interest Expense Growth QoQ', 'Sales Prev Q', 'Sales Prev YQ', 'EPS Prev Q',
                    'EPS Prev YQ', 'EBITDA Prev Q', 'EBITDA Prev YQ', 'Net Profit Prev Q', 'Net Profit Prev YQ', 'EBIT Prev Q', 'EBIT Prev YQ',
                    'Interest Exp Prev Q', 'Interest Exp Prev YQ', 'Depreciation Prev Q', 'Depreciation Prev YQ', 'Tax Prev Q', 'Tax Prev YQ',
                    'Other Income Prev Q', 'Other Income Prev YQ', 'Extraordinary Items Prev Q', 'Extraordinary Items Prev YQ',
                    'Equity Capital Prev Q', 'Equity Capital Prev YQ', 'PBT Prev Q', 'PBT Prev YQ', 'Sales 2Q Back', 'Sales 3Q Back',
                    'Net Profit 2Q Back', 'Net Profit 3Q Back', 'Operating Profit Prev Q', 'Operating Profit 2Q Back',
                    'Operating Profit 3Q Back', 'Operating Profit Prev YQ', 'OPM Prev Q', 'OPM Prev YQ', 'NPM Prev Q', 'NPM Prev YQ', 'EBIT FY',
                    'EBITDA FY', 'Employee Exp FY', 'EPS FY', 'Interest Expense Gross FY', 'PBT FY', 'Net Revenue FY', 'Gross Profit FY',
                    'R&D total FY', 'R&D to Sales FY %', 'Depreciation FY', 'Income Tax FY', 'Current Tax FY', 'Other Income FY',
                    'Extraordinary Items FY', 'Material Cost FY', 'Cost of Revenue ex Dep FY', 'Operating Profit FY', 'Payable to Sales %',
                    'Receivable Turnover', 'Asset Turnover FY', 'Cash ratio FY', 'Cash flow ROA FY', 'CFROCE FY', 'Current ratio FY',
                    'Debt to Assets FY', 'Debt to EBITDA FY', 'Debt to Equity FY', 'Fixed Asset Turnover', 'Interest Coverage Ratio FY', 
                    'Inventory Days', 'Inventory Turnover', 'Payables Days', 'Quick ratio FY', 'Receivables Days', 'ROA FY', 'ROE FY', 
                    'ROCE FY', 'ROIC FY', 'CF Accrual Ratio', 'Piotroski F-Score', 'Beneish M-Score', 'Montier C-Score',
                    'Cash Conversion Cycle', 'Working Capital Days', 'Earning Power', 'Financial Leverage', 'Current Assets FY End',
                    'BPS FY End', 'Cash and ST Inv FY End', 'Cash and Cash Eq FY End', 'Common Equity FY End', 'Shares outstanding FY End',
                    'Total Debt FY End', 'Total Fixed Assets - Net', 'Inventories FY End', 'Current Liabilities FY End', 
                    'Long term debt to Equity', 'LT Debt FY End', 'Net Current Assets FY End', 'Net Debt to EBITDA FY',
                    'Net Debt to FCFF FY', 'Net Debt FY End', 'Net Operating Assets FY End', 'Operating Assets FY End', 'Gross Block FY End',
                    'Net Block FY End', 'Receivables FY End', 'Reserves and Surplus FY End', 'ST Debt FY End', 'Tangible Book Value',
                    'Tangible Total Equity', 'Total Assets FY End', 'Total capital FY End', 'Total liabilities FY End', 
                    'Accumulated Depreciation', 'Revaluation Reserve', 'Total Investments', 'Equity Capital', 'Lease Liabilities', 'CWIP', 
                    'Trade Payables', 'Capex FY growth 1Y', 'Capex CF FY', 'Capex to Sales FY %', 'FCF to Earnings %', 'Financing CF FY', 
                    'Free Cash Flow FY', 'Investing CF FY', 'OCF to Earnings %', 'Operating CF ratio FY', 'Operating CF FY', 'FCFE FY', 
                    'FCFF FY', 'Cash Beginning Balance', 'Cash Ending Balance', 'Net Cash Flow', 'EBITDA margin FY', 'Gross margin FY', 
                    'Profit after Tax FY', 'Net profit margin FY', 'Operating CF margin FY', 'Operating margin FY', 'Free CF margin FY', 
                    'ROE 3Y Avg', 'ROE 5Y Avg', 'ROE 7Y Avg', 'ROE 10Y Avg', 'ROA 3Y Avg', 'ROA 5Y Avg', 'ROA 7Y Avg', 'ROA 10Y Avg', 
                    'ROCE 3Y Avg', 'ROCE 5Y Avg', 'ROCE 7Y Avg', 'ROCE 10Y Avg', 'ROIC 3Y Avg', 'ROIC 5Y Avg', 'NPM 3Y Avg', 'NPM 5Y Avg', 
                    'EBITDA Margin 3Y Avg', 'EBITDA Margin 5Y Avg', 'Gross Margin 3Y Avg', 'Gross Margin 5Y Avg', 'FCF Margin 3Y Avg', 
                    'FCF Margin 5Y Avg', 'OCF Margin 3Y Avg', 'OCF Margin 5Y Avg', 'OPM 3Y Avg', 'OPM 5Y Avg', 'OPM 10Y Avg', 
                    'Receivable Days 3Y Avg', 'Receivable Days 5Y Avg', 'Dividend Payout 3Y Avg', 'DPS 5Y Avg', 'Earnings 5Y Avg', 
                    'Earnings 10Y Avg', 'EBIT 5Y Avg', 'EBIT 10Y Avg', 'Working Capital Days 3Y Avg', 'Profit FY growth 1Y', 
                    'Sales FY growth 1Y', 'Sales FY 3Y CAGR', 'Sales FY 5Y CAGR', 'Sales FY 7Y CAGR', 'Sales FY 10Y CAGR', 'Profit FY 3Y CAGR',
                    'Profit FY 5Y CAGR', 'Profit FY 7Y CAGR', 'Profit FY 10Y CAGR', 'EBITDA FY 3Y CAGR', 'EBITDA FY 5Y CAGR', 
                    'EBITDA FY 7Y CAGR', 'EBITDA FY 10Y CAGR', 'FCF 3Y CAGR', 'FCF 5Y CAGR', 'FCF 7Y CAGR', 'CFO FY growth 1Y', 'CFO 3Y CAGR', 
                    'CFO 5Y CAGR', 'CFO 7Y CAGR', 'Capex FY 5Y CAGR', 'EPS FY growth 1Y', 'EPS FY 3Y CAGR', 'EPS FY 5Y CAGR', 'EPS FY 7Y CAGR', 
                    'EPS FY 10Y CAGR', 'BPS FY growth 1Y', 'BPS FY 3Y CAGR', 'BPS FY 5Y CAGR', 'Dividend growth 1Y', 'Dividend 3Y CAGR', 
                    'Dividend 5Y CAGR', 'Operating Profit Growth FY', 'Book to Market', 'Dividend yield', 'Earnings yield', 'EBIT yield', 
                    'EBITDA yield', 'Enterprise value', 'EV EBIT', 'EV EBITDA', 'EV Sales', 'FCF yield', 'Market Cap', 'Operating CF yield', 
                    'PB', 'PE', 'PS', 'P/FCF', 'PEG Ratio TTM', 'Shareholder Yield TTM', 'Graham Number', 'Dividend per Share', 
                    'Dividend Payout Ratio', 'Beta 1Y', 'Idiosyncratic return 1D', 'Momentum 1M', 'Momentum 3M', 'Momentum 6M', 
                    'Momentum 12M', 'Momentum 3M ex 1M', 'Momentum 6M ex 1M', 'Momentum 12M ex 1M', 'Momentum Score', 'Volatility 1M', 
                    'Volatility 3M', 'Volatility 1Y', 'Volatility Score', 'Price / 52W High', 'Return 1D', 'EBITDA Last Yr', 'EBITDA Prev Yr', 
                    'EBIT Last Yr', 'EBIT Prev Yr', 'Sales Last Yr', 'Sales Prev Yr', 'Net Profit Last Yr', 'Net Profit Prev Yr', 'PBT Last Yr', 
                    'PBT Prev Yr', 'Interest Exp Last Yr', 'Interest Exp Prev Yr', 'Depreciation Last Yr', 'Depreciation Prev Yr', 
                    'Employee Cost Last Yr', 'Dividend Last Yr', 'Dividend Prev Yr', 'Operating Profit Last Yr', 'Operating Profit Prev Yr', 
                    'Net Cash Flow Last Yr', 'Net Cash Flow Prev Yr', 'Cash Beginning Last Yr', 'Cash Beginning Prev Yr', 'Cash End Last Yr', 
                    'Cash End Prev Yr', 'Extraordinary Items Last Yr', 'Extraordinary Items Prev Yr', 'Material Cost Last Yr', 
                    'Operating CF Last Yr', 'Operating CF Prev Yr', 'Investing CF Last Yr', 'Investing CF Prev Yr', 'Financing CF Last Yr', 
                    'Financing CF Prev Yr', 'Free CF Last Yr', 'Free CF Prev Yr', 'Debt Prev Yr', 'Debt 3Y Back', 'Debt 5Y Back', 
                    'Debt 7Y Back', 'Debt 10Y Back', 'Cash 3Y Back', 'Cash 5Y Back', 'Cash 7Y Back', 'Net Block Prev Yr', 'Net Block 3Y Back', 
                    'Net Block 5Y Back', 'Net Block 7Y Back', 'Gross Block Prev Yr', 'Shares Prev Yr', 'Shares 10Y Back', 
                    'Investing CF 3Y Cumulative', 'Investing CF 5Y Cumulative', 'Investing CF 7Y Cumulative', 'Investing CF 10Y Cumulative', 
                    'Operating CF 3Y Cumulative', 'Operating CF 5Y Cumulative', 'Operating CF 7Y Cumulative', 'Operating CF 10Y Cumulative', 
                    'Free CF 3Y Cumulative', 'Free CF 5Y Cumulative', 'Free CF 7Y Cumulative', 'Free CF 10Y Cumulative', 'BPS Prev Yr', 
                    'BPS 3Y Back', 'BPS 5Y Back', 'BPS 10Y Back', 'Working Capital Prev Yr', 'Working Capital 3Y Back', 'Working Capital 5Y Back', 
                    'Working Capital 7Y Back', 'Working Capital 10Y Back', 'Inventory Turnover 3Y Back', 'Inventory Turnover 5Y Back', 
                    'Inventory Turnover 7Y Back', 'Inventory Turnover 10Y Back', 'OPM Last Yr', 'OPM Prev Yr', 'NPM Last Yr', 'NPM Prev Yr', 
                    'ROA Prev Yr', 'ROCE Prev Yr', 'ROE Prev Yr', 'EPS Last Yr', 'EPS Prev Yr', 'Sales TTM', 'Net Profit TTM', 'EBITDA TTM', 
                    'EBIT TTM', 'Operating CF TTM', 'Free CF TTM', 'EPS TTM', 'Equity TTM', 'Dividends Paid TTM', 'Gross Margin TTM', 
                    'EBITDA Margin TTM', 'Operating Margin TTM', 'Net Margin TTM', 'FCF Margin TTM', 'OCF Margin TTM', 'ROA TTM', 'ROE TTM', 
                    'ROCE TTM', 'ROIC TTM', 'Debt to Equity TTM', 'Debt to EBITDA TTM', 'Net Debt to EBITDA TTM', 'Interest Coverage TTM', 
                    'Current Ratio TTM', 'Inventory Days TTM', 'Receivable Days TTM', 'Payable Days TTM', 'Cash Conversion Cycle TTM', 
                    'Working Capital Days TTM', 'Asset Turnover TTM', 'BPS TTM', 'DPS TTM', 'OCF to Earnings TTM', 'FCF to Earnings TTM', 
                    'Capex to Sales TTM', 'Dividend Payout TTM', 'Sales Growth YoY TTM', 'EBITDA Growth YoY TTM', 'Profit Growth YoY TTM', 
                    'EPS Growth YoY TTM', 'FCF Growth YoY TTM', 'Piotroski Score TTM']


import re
import json

def validate_metrics(proposed, available) -> list[str]:
    """
    Keep only metrics whose names exactly match the available list.
    For near-misses (e.g. 'RSI' vs 'RSI 14'), attempt a fuzzy fallback
    so we don't silently drop useful metrics.
    """
    available_set = set(available)
    valid = []
    skipped = []

    for m in proposed:
        if m in available_set:
            valid.append(m)
        else:
            # Case-insensitive exact match
            lower_map = {a.lower(): a for a in available}
            if m.lower() in lower_map:
                valid.append(lower_map[m.lower()])
            else:
                # Prefix match: "RSI" → "RSI 14", "EMA" → "EMA 20" (first hit)
                prefix_hits = [a for a in available if a.lower().startswith(m.lower() + " ") or a.lower() == m.lower()]
                if prefix_hits:
                    valid.append(prefix_hits[0])
                else:
                    skipped.append(m)

    if skipped:
        print(f"⚠️  Dropped hallucinated metrics (not in metrics_constant): {skipped}")

    return valid


def validated_filters(raw_filters, available) -> list[FilterCondition]:
    """Validate metric names in filter conditions and drop invalid ones.
    Supports both value and metric comparisons."""
    available_set = set(available)
    valid = []
    skipped = []

    for f in raw_filters:
        metric = f.get("metric")
        compare_type = f.get("compare_type", "value")  # Default to "value" for backward compat

        # Validate primary metric
        if metric not in available_set:
            corrected = validate_metrics([metric], available)
            if not corrected:
                skipped.append(f"{metric} (primary metric not found)")
                continue
            metric = corrected[0]

        if compare_type == "metric":
            compare_metric = f.get("compare_metric")
            if not compare_metric:
                skipped.append(f"{metric} (missing compare_metric for metric comparison)")
                continue
            if compare_metric not in available_set:
                corrected = validate_metrics([compare_metric], available)
                if not corrected:
                    skipped.append(f"{metric} vs {compare_metric} (compare_metric not found)")
                    continue
                compare_metric = corrected[0]
            if metric.lower() == compare_metric.lower():
                skipped.append(f"{metric} (cannot compare metric to itself)")
                continue
            valid.append(FilterCondition(
                metric=metric,
                operator=f["operator"],
                compare_type="metric",
                value=None,
                compare_metric=compare_metric
            ))
        elif compare_type == "value":
            value = f.get("value")
            if value is None:
                skipped.append(f"{metric} (missing value for value comparison)")
                continue
            valid.append(FilterCondition(
                metric=metric,
                operator=f["operator"],
                compare_type="value",
                value=float(value),
                compare_metric=None
            ))
        else:
            skipped.append(f"{metric} (unknown compare_type: {compare_type})")

    if skipped:
        print(f"⚠️  Dropped invalid filters: {skipped}")

    return valid

def _fmt_filter(f) -> str:
    rhs = f["compare_metric"] if f.get("compare_type") == "metric" else f.get("value")
    return f"{f['metric']} {f['operator']} {rhs}"

def extract_json(text: str):
    """Try multiple strategies to extract valid JSON from LLM output."""
    text = text.strip()

    # Strategy 1: direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Strategy 2: strip markdown fences
    cleaned = (
        text
        .removeprefix("```json")
        .removeprefix("```")
        .removesuffix("```")
        .strip()
    )
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Strategy 3: find first {...} or [...] block using regex (handles nesting)
    match = re.search(r'(\{[\s\S]*\}|\[[\s\S]*\])', cleaned)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    raise ValueError(f"Could not parse JSON from LLM response:\n{text}")

from langchain_groq import ChatGroq
from dotenv import load_dotenv
import os
from groq import AuthenticationError, RateLimitError
 
load_dotenv()
 
_GROQ_KEY_1 = os.getenv("GROQ_API_KEY_1")
_GROQ_KEY_2 = os.getenv("GROQ_API_KEY_2")
_MODEL = "llama-3.3-70b-versatile"
 
if not _GROQ_KEY_1 or not _GROQ_KEY_2:
    raise EnvironmentError("GROQ_API_KEY_1 and GROQ_API_KEY_2 must both be set in your .env file.")
 
 
from langchain_core.runnables import Runnable
from langchain_core.messages import BaseMessage

class _FallbackLLM(Runnable):
    """Drop-in ChatGroq replacement that falls back to a secondary key on auth/rate-limit errors.
    Extends Runnable so `prompt | llm` works natively with LangChain."""

    def __init__(self, key1: str, key2: str, model: str):
        self._primary   = ChatGroq(model=model, api_key=key1)
        self._secondary = ChatGroq(model=model, api_key=key2)

    def invoke(self, input, config=None, **kwargs):
        try:
            return self._primary.invoke(input, config=config, **kwargs)
        except (AuthenticationError, RateLimitError) as e:
            print(f"⚠️  Primary API key failed ({type(e).__name__}). Switching to secondary key.")
            return self._secondary.invoke(input, config=config, **kwargs)


llm = _FallbackLLM(_GROQ_KEY_1, _GROQ_KEY_2, _MODEL)

# Cheap LLM for conversational clarification rounds
_CHAT_MODEL = "llama-3.1-8b-instant"
chat_llm = _FallbackLLM(_GROQ_KEY_1, _GROQ_KEY_2, _CHAT_MODEL)


"""## Graph State"""

class State(TypedDict):
    # Step 1
    input: str
    # Step 1.1 (new: conversation history)
    clarification_history: List[Tuple[str, str]]  # List of (question, user_answer) pairs
    awaiting_clarification: bool                  # If True, waiting for user response
    clarification_rounds: int                     # Number of clarification rounds so far
    clarification_attempts_max: int               # Max clarification rounds before proceeding
    latest_clarification_question: Optional[str] # Stores the latest question to ask the user
    # Step 1.2
    enriched_input: str
    metrics: List[str]
    # Step 2
    universe: str
    # Step 3
    filters: List[FilterCondition]        # e.g. [{"metric": "P/E Ratio", "operator": "<", "value": 40}]
    # Step 4
    ranking_metrics: List[str]
    # Step 5
    top_n: int                            # How many stocks to pick
    # Step 5.1
    weight_type: Literal["equal", "metric"]
    # Step 5.2 — only populated if weight_type == "metric"
    weight_metrics: List[str]
    reasoning: Reasoning
    # Step 6 - Modification Node
    mod_conversation: List[tuple]
    latest_mod_plan: Optional[str]
    # Step 7 - Ending workflow
    is_complete: bool

from langchain_core.prompts import ChatPromptTemplate
import json

#####################################################
#___________________INPUT_NODE_______________________
#####################################################
def clarification_node(state: State) -> State:
    """
    Decide whether the user's input is sufficiently detailed for strategy building,
    or if a clarifying question would improve the result.
    Returns state with either:
    - awaiting_clarification=True, with a question for the user
    - awaiting_clarification=False, ready to proceed to enrichment
    """
    # Build context from conversation history
    history_text = ""
    if state.get("clarification_history"):
        history_text = "Prior clarification conversation:\n"
        for i, (q, a) in enumerate(state["clarification_history"], 1):
            history_text += f"  Q{i}: {q}\n  A{i}: {a}\n"

    prompt = ChatPromptTemplate.from_template(
        """You are a clarifying assistant for quantitative trading strategies.
Your job is to decide: does the user's strategy description have enough detail for us to build a comprehensive stock screener (making reasonable assumptions where necessary), or is it so genuinely vague or missing critical elements that we cannot make any reasonable assumptions and must ask ONE clarifying follow‑up question first?

User's strategy description:
{input}

{history}

Decision rules:
1. ONLY ask for clarification (respond "clarify") if the input is missing enough key dimensions (such as thesis, target universe, or holding intent) that a reasonable assumption cannot be made, or if there is a direct contradiction in the request. Otherwise, respond "sufficient".
2. Partial vagueness is completely fine: if the input provides at least some direction, the system should make a reasonable assumption (e.g., standard holding period, standard large-cap universe, etc.) rather than asking.
3. Cap the conversation: if we've already asked {max_rounds} clarifying questions, proceed with best assumptions (respond "sufficient").

Examples of "sufficient" inputs (Do NOT ask a clarifying question for these, respond "sufficient"):
- Input: "Buy Nifty 50 stocks with high dividend yield." (Sufficient: target universe Nifty 50 and thesis dividend yield are clear; holding period and risk can be assumed).
- Input: "I want a strategy that buys fast-growing small-cap stocks with good earnings growth YoY." (Sufficient: thesis growth and target small-cap are clear).
- Input: "Buy stocks when RSI 14 crosses above 50." (Sufficient: entry signal RSI cross is clear; universe and holding period can be assumed).

Examples of "clarify" inputs (Requires asking a clarifying question):
- Input: "I want to make money trading stocks." (Clarify: Completely lacks thesis, target universe, holding intent, or any signal. Question: "Are you looking for short-term momentum trades or long-term value investments?")
- Input: "Buy something that is going up or down depending on the day." (Clarify: Contradictory and extremely vague. Question: "Are you looking for a trend-following strategy or a mean-reversion strategy?")

Respond ONLY with a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"decision": "sufficient|clarify", "question": "<question here, or null if sufficient>"}}
"""
    )
    chain = prompt | chat_llm
    response = chain.invoke({
        "input": state["input"],
        "history": history_text,
        "max_rounds": state["clarification_attempts_max"]
    })
    try:
        parsed = extract_json(response.content.strip())
    except Exception:
        print("⚠️ Invalid JSON from clarification LLM. Defaulting to proceed.")
        parsed = {"decision": "sufficient", "question": None}

    decision = parsed.get("decision", "sufficient")
    question = parsed.get("question")
    if decision == "clarify" and question and state["clarification_rounds"] < state["clarification_attempts_max"]:
        print(f"❓ Clarification Q{state['clarification_rounds'] + 1}: {question}")
        return {
            **state,
            "awaiting_clarification": True,
            "latest_clarification_question": question,
        }
    else:
        print("✅ Sufficient detail. Proceeding to strategy enrichment.")
        return {
            **state,
            "awaiting_clarification": False,
            "latest_clarification_question": None,
        }

#___________________INPUT_NODE_______________________

def take_input(state:State) -> State:
    user_input = input("🟢 Paste the strategy description here:\n")
    prompt = ChatPromptTemplate.from_template(
        """You are a quantitative trading strategy analyst. A user has described an investment strategy in their own words — it may be technical or plain language. Your job is to expand it into a precise, implementation-ready breakdown that downstream systems will use to screen and rank stocks.

Respond ONLY with a bullet-point breakdown using exactly these six sections. Do not add commentary, preamble, or a summary outside this structure.

- Core thesis: The market pattern or inefficiency this strategy exploits.
- Target stocks: Company characteristics to look for — size, sector, liquidity, growth vs. value orientation.
- Entry criteria: Specific conditions a stock must meet — technical signals, fundamental thresholds, price action, valuation limits. Be quantitative where possible (e.g. "RSI 14 above 55", "P/E below 20").
- Ranking logic: What separates the best picks from merely eligible ones. List signals in priority order.
- Risk profile: Aggressive / balanced / conservative. Note expected volatility tolerance and any concentration limits.
- Holding intent: Short-term trade (days–weeks) or medium/long-term investment (months–years).

Rules:
- Each bullet should be 1–3 sentences.
- Prefer numbers and thresholds over vague language. "Momentum above peers" is too vague; "3-month return in top 30% of universe" is good.
- If the user's input is ambiguous, make a reasonable assumption and state it in parentheses — e.g. (assumed: large-cap bias given mention of stability).
- Never ask the user a clarifying question.

User Input : {input}"""
    )
    enriched_input= prompt | llm
    enriched_input = enriched_input.invoke(
        {"input":user_input}
    )

    print("🔴 " + enriched_input.content)

    return {
        **state,
        "input":user_input,
        'enriched_input': enriched_input.content
    }



#####################################################
#___________________UNIVERSE_NODE____________________
#####################################################

def universe_node(state: State) -> State:
    prompt = ChatPromptTemplate.from_template(
        """You are a stock universe selector for an Indian equity screener.

You will be given a strategy description and a list of available stock universes.
Your task is to pick the single most appropriate universe for this strategy.

Guidelines:
- Broader universes (e.g. Nifty 500, All Universe) suit diversified or fundamental strategies with no strong size bias.
- Narrower universes (e.g. Nifty 50, Nifty Next 50) suit strategies that explicitly target large-caps or blue chips.
- Midcap/Smallcap/Microcap universes suit strategies that mention higher risk tolerance, growth, or smaller companies.
- Nifty FNO suits strategies involving derivatives, hedging, or high liquidity requirements.
- If the strategy mentions a specific index or segment, prefer that directly.
- When in doubt, prefer a broader universe over a narrower one.

Strategy description:
{strategy}

Available universes:
{universes}

Respond with ONLY a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"universe": "<name exactly as it appears in the list above>", "reasoning": "<1-2 sentences explaining why this universe fits the strategy>"}}"""
    )

    chain = prompt | llm
    response = chain.invoke({
        "strategy": state["enriched_input"],
        "universes": universes_constant
    })

    try:
        parsed = extract_json(response.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response = chain.invoke({
            "strategy": state["enriched_input"],
            "universes": universes_constant
        })
        parsed = extract_json(response.content.strip())


    selected_universe = parsed["universe"]
    reasoning = parsed["reasoning"]

    # Validate the selected universe
    if selected_universe.lower() not in [u.lower() for u in universes_constant]: # Case-insensitive check
        print(f"⚠️  Hallucinated universe '{selected_universe}' not found in available universes. Defaulting to 'All Universe'.")
        selected_universe = "All Universe"
        reasoning += " (Defaulted to 'All Universe' due to hallucinated universe selection.)"

    print("🟢 Stock Universe: "+selected_universe)
    print("🔴 Reasoning behind this Universe " + reasoning)

    return {
        **state,
        "universe": selected_universe,
        "reasoning": {
            **state.get("reasoning", {}),
            "universe": reasoning
        }
    }


#####################################################
#___________________FILTER_NODE_____________________#
#####################################################

def filter_node(state: State) -> State:

    # --- Step 1: Select relevant metrics ---
    prompt_1 = ChatPromptTemplate.from_template(
        """You are a quantitative stock screener assistant for Indian equities.

Given the strategy description below, select the most relevant filtration metrics from the provided list.
Only choose metrics that would serve as hard filters — i.e. thresholds a stock MUST meet to be considered.
Do not include metrics better suited for ranking/scoring.
Choose between 3 and 8 metrics. Only use names exactly as they appear in the list.

Strategy:
{strategy}

Available metrics:
{metrics_list}

Respond with ONLY a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"metrics": ["metric1", "metric2", ...], "reasoning": "<2-3 sentences explaining why these metrics were chosen as filters for this strategy>"}}"""
    )

    chain_1 = prompt_1 | llm
    response_1 = chain_1.invoke({
        "strategy": state["enriched_input"],
        "metrics_list": metrics_constant
    })
    try:
        parsed_1 = extract_json(response_1.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response_1 = chain_1.invoke({
            "strategy": state["enriched_input"],
            "metrics_list": metrics_constant
        })
        parsed_1 = extract_json(response_1.content.strip())

    # Validate selected metrics from the first prompt
    validated_selected_metrics = validate_metrics(parsed_1["metrics"], metrics_constant)
    if not validated_selected_metrics:
        print("⚠️ No valid metrics selected for filtering. Returning empty filters.")
        return {
            **state,
            "filters": [],
            "reasoning": {
                **state.get("reasoning", {}),
                "filter": parsed_1["reasoning"] + " (No valid metrics found for filtering)."
            },
            "metrics": metrics_constant
        }

    # --- Step 2: Assign operator and threshold value/metric to each metric ---
    prompt_2 = ChatPromptTemplate.from_template(
        """You are a quantitative stock screener assistant for Indian equities.

For each metric below, assign an appropriate comparison operator and threshold
that would serve as a sensible filter given the strategy context.

You can compare a metric to:
1. A static value (e.g., RSI 14 > 55, P/E < 20)
2. Another metric (e.g., EMA 20 > EMA 50, Close Price > EMA 50)

Rules:
- Operator must be one of: ">", "<", ">=", "<=", "=="
- For VALUE comparisons: value must be a number (int or float). No strings, no nulls.
- For METRIC comparisons: the second metric must also be from the available metrics list.
- Use domain knowledge: momentum strategies benefit from moving average crossovers (metric vs metric),
  value strategies use valuation thresholds (metric vs value).
- Ensure filters are realistic for Indian equities.

Strategy:
{strategy}

Stock Universe:
{universe}

Metrics to assign (use exact names):
{metrics}

Respond with ONLY a JSON array. Each element must be one of these two shapes:
  Value comparison : {{"metric": "METRIC_NAME", "operator": "OP", "compare_type": "value", "value": NUMBER}}
  Metric comparison: {{"metric": "METRIC_NAME", "operator": "OP", "compare_type": "metric", "compare_metric": "METRIC2_NAME"}}
No extra text, no markdown, no code fences."""
    )

    chain_2 = prompt_2 | llm
    response_2 = chain_2.invoke({
        "strategy": state["enriched_input"],
        "metrics": "\n".join(validated_selected_metrics), # Use validated metrics here
        "universe": state['universe']
    })
    try:
        parsed_2 = extract_json(response_2.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response_2 = chain_2.invoke({
            "strategy": state["enriched_input"],
            "metrics": "\n".join(validated_selected_metrics),
            "universe": state['universe']
        })
        parsed_2 = extract_json(response_2.content.strip())

    # Validate the filter conditions produced by the second prompt
    validated_filter_conditions = validated_filters(parsed_2, metrics_constant)

    filters: List[FilterCondition] = []
    for item in validated_filter_conditions:
        compare_type = item.get("compare_type", "value")
        if compare_type == "metric":
            filters.append(FilterCondition(
                metric=item["metric"],
                operator=item["operator"],
                compare_type="metric",
                value=None,
                compare_metric=item.get("compare_metric"),
            ))
        else:
            raw_val = item.get("value")
            try:
                val = float(raw_val) if raw_val is not None else 0.0
            except (TypeError, ValueError):
                val = 0.0
            filters.append(FilterCondition(
                metric=item["metric"],
                operator=item["operator"],
                compare_type="value",
                value=val,
                compare_metric=None,
            ))
    print("🟢 Filters Applied: ", filters)
    print("🔴 Reasoning behind Filters: ", parsed_1["reasoning"])
    return {
        **state,
        "filters": filters,
        "reasoning": {
            **state.get("reasoning", {}),
            "filter": parsed_1["reasoning"]
        },
        "metrics":metrics_constant
    }


#####################################################
#___________________RANKING_NODE_____________________
#####################################################
def ranking_node(state: State) -> State:
    prompt = ChatPromptTemplate.from_template(
        """You are a quantitative stock screener assistant for Indian equities.

Given the strategy and selected universe below, choose 2-8 metrics to SCORE and RANK stocks against each other.

Important distinctions:
- Ranking metrics are used to order eligible stocks by quality — higher is better (or lower, depending on metric).
- Do NOT repeat metrics already used as hard filters: {filters}
- Prefer metrics that differentiate quality within the universe, not just eligibility.
- For momentum strategies, prefer return and momentum metrics.
- For value strategies, prefer valuation and earnings metrics.
- For quality strategies, prefer profitability and stability metrics.
- Choose metrics that are likely to be populated for stocks in {universe} (e.g. avoid quarterly earnings metrics for microcaps).

Strategy:
{strategy}

Available metrics:
{metrics}

Respond with ONLY a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"metrics": ["inverse metric1", "metric2", ...], "reasoning": "<2-3 sentences explaining why these metrics rank stock quality for this specific strategy>"}}"""
    )

    chain = prompt | llm
    response = chain.invoke({
        "universe": state["universe"],
        "strategy": state["enriched_input"],
        "metrics": "\n".join(state["metrics"]),
        "filters": ", ".join(f["metric"] for f in state["filters"])
    })

    try:
        parsed = extract_json(response.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response = chain.invoke({
            "universe": state["universe"],
            "strategy": state["enriched_input"],
            "metrics": "\n".join(state["metrics"]),
            "filters": ", ".join(f["metric"] for f in state["filters"])
        })
        parsed = extract_json(response.content.strip())

    # Validate ranking metrics
    validated_ranking_metrics = validate_metrics(parsed["metrics"], state["metrics"])

    print("🟢 Ranking Metrics: ", validated_ranking_metrics)
    print("🔴 Reasoning: ", parsed["reasoning"])

    return {
        **state,
        "ranking_metrics": validated_ranking_metrics,
        "reasoning": {
            **state.get("reasoning", {}),
            "rank": parsed["reasoning"]
        }
    }


#####################################################
#__________________WEIGHTAGE_NODE____________________
#####################################################

def weightage_node(state: State) -> State:
    prompt = ChatPromptTemplate.from_template(
        """Based on the given strategy, stock universe and ranking metrics
    answer the following Questions

    strategy: {strategy}
    stock universe: {universe}
    filtration metrics: {filtration}
    ranked based on: {rank_metrics}
    1. How many of the top ranked stocks should be added in our strategy?
    2. Should the weightage given to each stock be equal or based on some metric?

    Respond with ONLY a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"num_stocks": <integer>, "weightage": <either "equal" or "metric">}}"""
    )

    chain = prompt | llm
    response = chain.invoke({
        "universe": state["universe"],
        "strategy": state["enriched_input"],
        "filtration": ", ".join(
            _fmt_filter(f) for f in state["filters"]
        ),
        "rank_metrics": ", ".join(state["ranking_metrics"]),
    })

    try:
        parsed = extract_json(response.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response = chain.invoke({
            "universe": state["universe"],
            "strategy": state["enriched_input"],
            "filtration": ", ".join(_fmt_filter(f) for f in state["filters"]),
            "rank_metrics": ", ".join(state["ranking_metrics"]),
        })
        parsed = extract_json(response.content.strip())

    prompt_2 = ChatPromptTemplate.from_template(
        """Based on the given strategy, stock universe and ranking metrics
answer the following Questions

strategy: {strategy}
stock universe: {universe}
filtration metrics: {filtration}
ranked based on: {rank_metrics}
available_metrics: {metrics}

1. What metric should be used to assign the weight of each stock in our strategy? (Choose only from the available metrics)

Respond with ONLY a JSON object in exactly this format, with no extra text, no markdown, no code fences:
{{"inverse": <either "inverse" or " ">, "metric": <Choose one from "available metrics">}}"""
    )

    if parsed["weightage"].lower() == "metric":
        chain = prompt_2 | llm
        response_2 = chain.invoke({
            "universe": state["universe"],
            "strategy": state["enriched_input"],
            "metrics": "\n".join(state["metrics"]),
            "filtration": ", ".join(
                _fmt_filter(f) for f in state["filters"]
            ),
            "rank_metrics": ", ".join(state["ranking_metrics"]),
        })

        try:
            parsed_2 = extract_json(response_2.content.strip())
        except:
            print("⚠️ Invalid JSON Returned... Trying again")
            response_2 = chain.invoke({
                "universe": state["universe"],
                "strategy": state["enriched_input"],
                "metrics": "\n".join(state["metrics"]),
                "filtration": ", ".join(
                    _fmt_filter(f) for f in state["filters"]
                ),
                "rank_metrics": ", ".join(state["ranking_metrics"]),
            })
            parsed_2 = extract_json(response_2.content.strip())

        # Validate the metric proposed for weighting
        validated_weight_metric_list = validate_metrics([parsed_2["metric"]], state["metrics"])

        if parsed["weightage"].lower() == "metric" and validated_weight_metric_list:
            weight_type = "metric"
            weight_metrics = [parsed_2["inverse"], validated_weight_metric_list[0]]
        else:
            weight_type = "equal"
            weight_metrics = []

        return {
            **state,
            "top_n": parsed["num_stocks"],
            "weight_type": weight_type,
            "weight_metrics": weight_metrics,
            "reasoning": {
                **state.get("reasoning", {}),
                "weightage": f"Metric-based weighting using {parsed_2['metric']}"
                             + (" (inverse)" if parsed_2["inverse"] == "inverse" else ""),
            }
        }
    else:
        return {
            **state,
            "top_n": parsed["num_stocks"],
            "weight_type": "equal",
            "weight_metrics": [],
            "reasoning": {
                **state.get("reasoning", {}),
                "weightage": "Equal weighting applied across selected stocks.",
            }
        }


#####################################################
#___________________DISPLAY_NODE____________________#
#####################################################
def display_node(state: State) -> State:
    filters_str = "\n".join(
        f"    • {_fmt_filter(f)}"
        for f in state["filters"]
    )
    ranking_str = "\n".join(f"    {i+1}. {m}" for i, m in enumerate(state["ranking_metrics"]))

    if state["weight_type"] == "metric":
        inverse, metric = state["weight_metrics"][0], state["weight_metrics"][1]
        weight_str = f"Metric-based → {metric}" + (" (inverse)" if inverse == "inverse" else "")
    else:
        weight_str = "Equal weighting"

    print("""
╔══════════════════════════════════════════════════════════════╗
║                    📊 STRATEGY SUMMARY                       ║
╚══════════════════════════════════════════════════════════════╝

🌐 Universe:
{universe}

🔍 Filters:
{filters}

📈 Ranking Metrics:
{ranking}

⚖️ Weighting:    {weight}
🔢 Top N Stocks:  {top_n}

💡 Reasoning:
    Universe  → {r_universe}
    Filters   → {r_filter}
    Ranking   → {r_rank}
    Weighting → {r_weight}

══════════════════════════════════════════════════════════════

""".format(
        universe=state["universe"],
        filters=filters_str,
        ranking=ranking_str,
        weight=weight_str,
        top_n=state["top_n"],
        r_universe=state["reasoning"].get("universe", "—"),
        r_filter=state["reasoning"].get("filter", "—"),
        r_rank=state["reasoning"].get("rank", "—"),
        r_weight=state["reasoning"].get("weightage", "—"),
    ))

    completion = input("Would you like to modify this strategy? (yes/no)")

    if completion.lower() == "yes" or completion.lower() == 'y':
        return {
            **state,
            "is_complete": False}
    else:
        return {**state,
                'is_complete': True}

#####################################################
#________________MODIFICATION_NODE__________________#
#####################################################

def modification_node(state: State) -> State:
    filters_str = "\n".join(
        f"    • {_fmt_filter(f)}"
        for f in state["filters"]
    )
    ranking_str = "\n".join(f"    {i+1}. {m}" for i, m in enumerate(state["ranking_metrics"]))

    if state["weight_type"] == "metric":
        inverse, metric = state["weight_metrics"][0], state["weight_metrics"][1]
        weight_str = f"Metric-based → {metric}" + (" (inverse)" if inverse == "inverse" else "")
    else:
        weight_str = "Equal weighting"
    mod_input = input("Enter your modification plan:")

    conversation = [
        ('system', """\
You are a quantitative portfolio strategist specialising in Indian equities. \
A user wants to modify an existing screener strategy. Your job is to interpret \
their intent precisely and produce a concrete, implementation-ready modification plan.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CURRENT STRATEGY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Universe       : {universe}
Filters        : {filters}
Ranking metrics: {ranking}
Weighting      : {weight}
Top N stocks   : {top_n}

Reasoning on record:
  Universe  → {r_universe}
  Filters   → {r_filter}
  Ranking   → {r_rank}
  Weighting → {r_weight}""".format(
        universe=state["universe"],
        filters=filters_str,
        ranking=ranking_str,
        weight=weight_str,
        top_n=state["top_n"],
        r_universe=state["reasoning"].get("universe", "—"),
        r_filter=state["reasoning"].get("filter", "—"),
        r_rank=state["reasoning"].get("rank", "—"),
        r_weight=state["reasoning"].get("weightage", "—"),
        )
  ),

('human',"""━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
USER INSTRUCTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{instructions}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
YOUR TASK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Enrich the user instruction: infer any implicit intent and resolve ambiguity. \
   State your interpretation.

2. Produce a modification plan using ONLY these five sections. \
   Do not add, rename, or reorder them.

- Universe change  : State the new universe, or "No change" if unaffected. \
                     One sentence justifying the choice.
- Filter changes   : List each filter to ADD, REMOVE, or MODIFY as a bullet. \
                     Use the format → ADD / REMOVE / MODIFY | <metric> <operator> <value> | <reason>. \
                     Write "No change" if unaffected.
- Ranking changes  : List each ranking metric to ADD, REMOVE, or REORDER as a bullet \
                     using the same → ACTION | <metric> | <reason> format. \
                     Write "No change" if unaffected.
- Weighting change : State the new weighting scheme, or "No change". One sentence justifying it. weights can be applied based on a metric (like "PE Ratio") or equal.
- Top N change     : State the new number, or "No change". One sentence justifying it.

Rules:
- Be quantitative. "Increase momentum exposure" is not acceptable; \
  "ADD | 3-month price return | top momentum signal for medium-term strategies" is.
- Never suggest metrics that are not measurable or that require data outside a standard \
  Indian equity screener (e.g. management quality, ESG ratings without a numeric score).
- Do not restate parts of the strategy that are unchanged beyond writing "No change".
- If the user instruction contradicts the strategy's core thesis, flag it explicitly \
  before the modification plan with: ⚠ Conflict: <one sentence>.
""".format(
        instructions = mod_input
        )
    )
    ]

    enriched_mod = llm.invoke(conversation)

    print("🟡 Modification Plan:\n", enriched_mod.content.strip())
    conversation.append(('ai', enriched_mod.content.strip()))

    prompt = ('system', """Identify which sections need modification. Respond with ONLY a valid JSON object — no markdown, no code fences, no explanation.

Valid section names: "universe", "filters", "ranking_metrics", "weight_metrics", "top_n"

Format: {"sections": ["<section_name>", ...]}
Example: {"sections": ["universe", "filters", "top_n"]}""")

    conversation.append(prompt)
    response = llm.invoke(conversation)
    try:
        parsed = extract_json(response.content.strip())
    except:
        print("⚠️ Invalid JSON Returned... Trying again")
        response = llm.invoke(conversation)
        parsed = extract_json(response.content.strip())

    parsed = validate_metrics(parsed['sections'], ["universe", "filters", "ranking_metrics", "weight_metrics", "top_n"])

    state = {**state, "mod_conversation": conversation,
             "latest_mod_plan": enriched_mod.content.strip(),
             "enriched_input": f"ORIGINAL:\n{state['enriched_input']}\n\nMODIFICATION PLAN:\n{enriched_mod.content.strip()}"}

    SECTION_NODE_MAP = {
        "universe":        universe_node,
        "filters":         filter_node,
        "ranking_metrics": ranking_node,
        "weight_metrics":  weightage_node,
        "top_n":           weightage_node,
    }

    already_run = set()
    for section in parsed:
        node_fn = SECTION_NODE_MAP.get(section)
        if node_fn is None:
            print(f"⚠️ Unknown section '{section}', skipping.")
            continue
        if node_fn in already_run:
            continue
        print(f"🔄 Updating: {section}")
        state = node_fn(state)
        already_run.add(node_fn)

    return {
        **state,
        "mod_conversation": state.get("mod_conversation", []) + conversation,
        "is_complete": False,  # send back to display_node for review
    }

"""## Adding Edges"""

from langgraph.graph import START, END, StateGraph

# Routing Function
def route_from_display(state: State) -> str:
    return "modification_node" if not state.get("is_complete") else "END"

def create_workflow_graph():
    workflow = StateGraph(State)

    # Add nodes
    workflow.add_node("take_input",    take_input)
    workflow.add_node("universe_node", universe_node)
    workflow.add_node("filter_node",   filter_node)
    workflow.add_node("ranking_node",  ranking_node)
    workflow.add_node("weightage_node",weightage_node)
    workflow.add_node("display_node",  display_node)
    workflow.add_node("modification_node", modification_node)

    # Add Edges
    workflow.add_edge(START,            "take_input")
    workflow.add_edge("take_input",     "universe_node")
    workflow.add_edge("universe_node",  "filter_node")
    workflow.add_edge("filter_node",    "ranking_node")
    workflow.add_edge("ranking_node",   "weightage_node")
    workflow.add_edge("weightage_node", "display_node")

    workflow.add_conditional_edges("display_node",
                                   route_from_display,
                                   {
                                       "modification_node":"modification_node",
                                       "END":END
                                   }
                                   )
    workflow.add_edge("modification_node", "display_node")


    return workflow.compile()

app = create_workflow_graph()